name: Flyway Migration

on:
  push:
    branches:
      - master

jobs:
  migrate_dev:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: flyway.url=jdbc:postgresql://0.tcp.in.ngrok.io:12024/postgresdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Set up Flyway
        run: |
          curl -s "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.2.2/flyway-commandline-8.2.2.tar.gz" --output flyway.tar.gz
          tar -xf flyway.tar.gz
          export FLYWAY_HOME=$(pwd)/flyway-8.2.2

      - name: Run Flyway Migration (Dev)
        run: |
          ${{ env.FLYWAY_HOME }}/flyway -user=${{ env.DATABASE_USERNAME }} -password=${{ env.DATABASE_PASSWORD }} -url=${{ env.DATABASE_URL }} -locations=filesystem:db/migration migrate
