name: Flyway Migration

on:
  push:
    branches:
      - master

jobs:
  migrate_dev:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: flyway.url=jdbc:postgresql://0.tcp.in.ngrok.io:12024/postgresdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      FLYWAY_HOME: ${{ github.workspace }}/flyway-8.2.2
      FLYWAY_JAR: ${{ env.FLYWAY_HOME }}/flyway.jar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Flyway
        run: |
          curl -s "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.2.2/flyway-commandline-8.2.2.tar.gz" --output flyway.tar.gz
          tar -xf flyway.tar.gz
          mv flyway-8.2.2 ${{ env.FLYWAY_HOME }}

      - name: Run Flyway Migration (Dev)
        run: |
          java -cp ${{ env.FLYWAY_JAR }} org.flywaydb.commandline.Main -user=${{ env.DATABASE_USERNAME }} -password=${{ env.DATABASE_PASSWORD }} -url=${{ env.DATABASE_URL }} -locations=filesystem:${{ github.workspace }}/db/migration migrate


